blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/abhishekgarg-wiom/wiom-ds-android/discussions
    about: Ask a question or start a discussion (not a bug or feature request).
